export const SEED_PROJECTS = [
  {
    slug: 'reset-club',
    name: 'Reset Club',
    description: 'Ignition client project',
    category: 'client',
    status: 'active',
    color: '#6366f1',
    githubOwner: null,
    githubRepo: null,
    contractValue: 0,
    hourlyRate: null,
  },
  {
    slug: 'leenas-crossroads',
    name: "Leena's Crossroads",
    description: 'Ignition client project',
    category: 'client',
    status: 'active',
    color: '#f43f5e',
    githubOwner: null,
    githubRepo: null,
    contractValue: 0,
    hourlyRate: null,
  },
  {
    slug: 'selene',
    name: 'Selene',
    description: 'Personal build',
    category: 'personal',
    status: 'active',
    color: '#0ea5e9',
    githubOwner: 'YOUR_GH_USERNAME', // replace before syncing
    githubRepo: 'selene',
    contractValue: null,
    hourlyRate: null,
  },
  {
    slug: 'openclaw',
    name: 'OpenClaw',
    description: 'Personal build',
    category: 'personal',
    status: 'active',
    color: '#f97316',
    githubOwner: 'YOUR_GH_USERNAME', // replace before syncing
    githubRepo: 'openclaw',
    contractValue: null,
    hourlyRate: null,
  },
  {
    slug: 'ignition-ops',
    name: 'Ignition Ops',
    description: 'Own business operations',
    category: 'ops',
    status: 'active',
    color: '#10b981',
    githubOwner: null,
    githubRepo: null,
    contractValue: null,
    hourlyRate: null,
  },
  {
    slug: 'x-strategy',
    name: 'X Strategy',
    description: 'Personal content strategy',
    category: 'personal',
    status: 'active',
    color: '#a855f7',
    githubOwner: null,
    githubRepo: null,
    contractValue: null,
    hourlyRate: null,
  },
  {
    slug: 'property-search',
    name: 'Property Search',
    description: 'Personal property search',
    category: 'personal',
    status: 'active',
    color: '#eab308',
    githubOwner: null,
    githubRepo: null,
    contractValue: null,
    hourlyRate: null,
  },
] as const
